My first homework
KonstantinAndreev/golang-one pull request #1
Opened 2021-11-16 14:25 UTC by KonstantinAndreev

2021-11-16 14:53 UTC, v-lozhkin requested changes

2021-11-16 14:53 UTC, v-lozhkin commented on homework1/main.go
> +
Мелочь, но многовато пустых строк в конце. По стандарту нужна одна :) `go fmt` тоже оставляет одну

2021-11-23 09:18 UTC, merged

2021-11-23 09:20 UTC, KonstantinAndreev commented
Поправил. Но не уверен что правильно залил на GitHub

2021-11-23 09:59 UTC, KonstantinAndreev commented on homework1/main.go
> +
Поправил но неуверен что правильно загрузил на Git Hub